// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Original.Models;

namespace Original.Migrations
{
    [DbContext(typeof(OriginalContext))]
    partial class OriginalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Original.Models.Toregister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Altura");

                    b.Property<string>("CPF")
                        .IsRequired();

                    b.Property<int>("Idade");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("Nascimento");

                    b.Property<double>("Peso");

                    b.Property<string>("Sexo");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Toregister");
                });
#pragma warning restore 612, 618
        }
    }
}
